import {test,expect} from 'vitest';import {createServer} from 'node:http';import {OpenWorkV2} from '../src/adapters/openwork-v2-01857.js';
for(const f of [{qualified:false,writes:true,version:'0.18.57',expected:false},{qualified:true,writes:false,version:'0.18.57',expected:false},{qualified:true,writes:true,version:'new',expected:false},{qualified:true,writes:true,version:'0.18.57',expected:true}])test('default-model capability respects the independent qualification/version/write boundary '+JSON.stringify(f),async()=>{
 const server=createServer((_q,r)=>{r.setHeader('Content-Type','application/json');r.end(JSON.stringify({ok:true,version:f.version}))});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));
 try{const a=server.address();if(!a||typeof a==='string')throw Error('Port');const adapter=new OpenWorkV2(async()=>({origin:`http://127.0.0.1:${a.port}`,token:'synthetic'}),f.writes,undefined,false,false,false,false,false,false,false,f.qualified);await adapter.health();expect(adapter.capabilities.workspaceDefaults===true).toBe(f.expected)}finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()))}
});
for(const code of ['workspace_default_model_changed','unrelated_conflict'])test('only the native conditional rejection is known-safe: '+code,async()=>{
 let writes=0;const server=createServer((q,r)=>{r.setHeader('Content-Type','application/json');if(q.method==='PUT'){writes++;r.statusCode=409;r.end(JSON.stringify({code}));return}r.end(JSON.stringify(q.url==='/health'?{ok:true,version:'0.18.57'}:q.url?.endsWith('/model')?{data:[{providerID:'synthetic',id:'b',enabled:true,variants:[]}]}:{model:null,revision:'a'.repeat(64),conditionalWrite:true}))});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));
 try{const a=server.address();if(!a||typeof a==='string')throw Error('Port');const adapter=new OpenWorkV2(async()=>({origin:`http://127.0.0.1:${a.port}`,token:'synthetic'}),true,undefined,false,false,false,false,false,false,false,true);await adapter.health();await expect(adapter.setWorkspaceDefaults('owned',{providerId:'synthetic',modelId:'b',variant:null},'a'.repeat(64),new AbortController().signal)).rejects.toMatchObject({code:code==='workspace_default_model_changed'?'STALE_SETTINGS':'UPSTREAM_REJECTED'});expect(writes).toBe(1)}finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()))}
});
